### PR TITLE
Viktar-HW_34

### PR DESCRIPTION
**Pull request by Amicronpersej8**

### CODE REVIEW

**Review by jathpr — CHANGES_REQUESTED** [review]
plz, add `.gitignore` file with `node_modules` in it

**Comment by jathpr** [comment]
and HW done well

**Review by jathpr — CHANGES_REQUESTED** [review]
better, but node_modules is already committed, before gitignore
you need to make the last two commits as one
git revert or reset --soft will help. Not sure which of them. You can ask for help if needed.

**Comment by Amicronpersej8** [comment]
I reverted last commit. I hope I did it right.

**Review by jathpr — APPROVED** [review]
strange that PR say that you have 3 commits
but yes - all right!

**Pull request merged**
